/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.analysis.testing;

import java.io.PrintStream;

public class App {

    private final PrintStream stream;

    public App(PrintStream out) {
        stream = out;
    }

    public void greet() {
        stream.println(getGreeting());
    }

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        new App(System.out).greet();
    }
}
