/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.analysis.testing;

import java.io.PrintStream;

public class App {

    private final PrintStream stream;
    private final Greeter greeter;

    public App() {
        this(System.out);
    }

    public App(PrintStream out) {
        stream = out;
        greeter = new Greeter();
    }

    public void greet() {
        String greeting = greeter.greet("Hello", "World");
        stream.println(greeting);
    }

    public String getGreeting(String greeting, final String name) {
        if ("Oops".equals(greeting)) {
            return "Error!";
        } else if ("Manager".equals(name)) {
            String formalGreeting = "sudo " + greeting;
            return greeter.greet(formalGreeting, name);
        }
        return greeter.greet(greeting, name);
    }

    public static void main(String[] args) {
        new App(System.out).greet();
    }
}
