/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.analysis.testing;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App(System.out);
        assertNotNull(classUnderTest.getGreeting("World"), "app should have a greeting");
    }
}
